# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 015e4195cee094ce29ff7d8e91fa432f2c56af509a119312abcb99944158709e65ae8bc91e87ad7089453b86cd3d172df4783e98561721ad4db9a89b483683cb

test:
  secret_key_base: 9bb97bef79c0e076133e7f0471fbc2cb0d05594833f1c1218498bde8661cefa668037e05a6e9ab20614ad5605aded5f28dd5923b19133b04444d2b5e768cad6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
